version: '3'
services:
  app:
    container_name: JWTapi_app
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - db_postgres      
    networks:
      - jwtapi

  db_postgres:
    image: postgres:latest
    container_name: JWTapi_db
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - jwtapi

volumes:
  api:
  database_postgres:                  

networks:
  jwtapi:
    driver: bridge